!/bin/bash

clear
printf "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmMMMMMMMMMM
MMMMMMMMNhMMMMMMMMMMMMMMMMMMMNdhMmMMMMMM
MMMMMNNhdNMMMMMMMMMMMMMMMMMMMNmmsmmMMMMM
MMMMMysMMNMMMMMhNMMmMMMMMMMMNMNm/sMMMMMM
MMMMNshmMMMMNNMNMMNNMMMMMMMNMMNmh-sMMMMM
MMMMN:oNMMmdmdmMMMMMMMMMMMMmNdhMm-/MMMMM
MMMMm.-hNdNNNyNMMMMMMMMMMMMhmmmN+./MMMMM
MMMMd.-/ymmdmhmMMMMMMMMMMMNddmho-::NMMMM
MMMMh..-/oymNMmMMMMMMMMMMNmdhh...-:NMMMM
MMMMd:....-hyhyNMMMMMMMMMNymo:....:NMMMM
MMMMN+.....:yddMMMMMMMMmNNds:...:-yNMMMM
MMMMNmo---..-+ommNMMNdddms/-:.-.-ymMMMMM
MMMMNmNy.-.....sNMMMNNmy:..--.-/ydmMMMMM
MMMMNNdmo+:.....:+yMNy:....-..:shmNNMMMM
MMMMMNmdhmyo+//:+dMNNmy/://sdysyNNNNMMMN
MMMMMMMdhhdmmmmdyMMMMMNdmdddyydNNMMNMMMM
MMMMMMNNmho/+yddmMNMMdmmNdh+odNMMMNNMMMM
MNNNMNNdmdhso/o/yodmhhyos-/+hmNMMMMMMMMM
MMMmmhMhMMmdhs+:s/+o:s-o//sdNNMMMMMMMMMM
MMMMMNhhMMMmdhosy+os:s+/+sdNmMMMMMMMMMMM
MNMNMMMMMMMNdhhdhyyhsyyohhoNNNMMMMMMMMMM
MNMMMMMMMMMMyoydhhhdyhshdsoNNMMMMMMMMMMM
MMMMNMMNmMMMd/yddyhdhhods+yNMMMMMMMMMMMM
MMMMMMMMMMMMmyohyhdsdhhys+hmNMMMMMMMMMMM
MMMMMMMMMMNMMNy++dysyhs/osNNMMNMMMMMMMMM
MMMMMMMMMMMMMMho:oyo:ho+sNNNMMMMMMMMMMMM
MMMMMMMMMMMMMMMNooos:s+smNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNNmNNmhNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMmymNyhNmhhhdhdhNMMMMMMMMMMMM
MNNNNNMMMMMMMMMMNMMMNMMNMMNMMMMMMMMMMMMM"
sleep 3
chainging your interface



exit
