!/bin/bash

clear
printf "MMMMMMMMVENOMMMMMMMMMmMMMMMMMMMM
MMMMMMMMNhMMMMMMMMMMMMMMMMMMMNdhMmMMMMMM
MMMMMNNhdNMMMMMMMMMMMMMMMMMMMNmmsmmMMMMM
MMMMMysMMNMMMMMhNMMmMMMMMMMMNMNm/sMMMMMM
MMMMNshmMMMMNNMNMMNNMMMMMMMNMMNmh-sMMMMM
MMMMN:oNMMmdmdmMMMMMMMMMMMMmNdhMm-/MMMMM
MMMMm.-hNdNNNyNMMMMMMMMMMMMhmmmN+./MMMMM
MMMMd.-/ymmdmhmMMMMMMMMMMMNddmho-::NMMMM
MMMMh..-/oymNMmMMMMMMMMMMNmdhh...-:NMMMM
MMMMd:....-hyhyNMMMMMMMMMNymo:....:NMMMM
MMMMN+.....:yddMMMMMMMMmNNds:...:-yNMMMM
MMMMNmo---..-+ommNMMNdddms/-:.-.-ymMMMMM
MMMMNmNy.-.....sNMMMNNmy:..--.-/ydmMMMMM
MMMMNNdmo+:.....:+yMNy:....-..:shmNNMMMM
MMMMMNmdhmyo+//:+dMNNmy/://sdysyNNNNMMMN
MMMMMMMdhhdmmmmdyMMMMMNdmdddyydNNMMNMMMM
MMMMMMNNmho/+yddmMNMMdmmNdh+odNMMMNNMMMM
MNNNMNNdmdhso/o/yodmhhyos-/+hmNMMMMMMMMM
MMMmmhMhMMmdhs+:s/+o:s-o//sdNNMMMMMMMMMM
MMMMMNhhMMMmdhosy+os:s+/+sdNmMMMMMMMMMMM
MNMNMMMMMMMNdhhdhyyhsyyohhoNNNMMMMMMMMMM
MNMMMMMMMMMMyoydhhhdyhshdsoNNMMMMMMMMMMM
MMMMNMMNmMMMd/yddyhdhhods+yNMMMMMMMMMMMM
MMMMMMMMMMMMmyohyhdsdhhys+hmNMMMMMMMMMMM
MMMMMMMMMMNMMNy++dysyhs/osNNMMNMMMMMMMMM
MMMMMMMMMMMMMMho:oyo:ho+sNNNMMMMMMMMMMMM
MMMMMMMMMMMMMMMNooos:s+smNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNNmNNmhNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMmymNyhNmhhhdhdhNMMMMMMMMMMMM
MNNNNNMMMMMMMMMMNMMMNMMNMMNMMMMMMMMMMMMM"
sleep 3
printf "\nchainging your interface"


echo "PS1='\033[01;39m\]┌──\[\033[38;5;208m\]root\[\033[01;39m\]@\[\033[38;5;28m\]user \[\033[01;$ ~:
\[\033[01;39m\]└──╼\[\033[01;31m\]>\[\033[01;39m\]' " >> ~/.bash_profile

printf "\nNow restart your terminal"

sleep 5

exit
